# Generated by Django 4.2.7 on 2023-12-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=120)),
                ('extract', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=120)),
                ('postedBy', models.CharField(max_length=120)),
            ],
        ),
    ]
