# Generated by Django 4.2.7 on 2024-01-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0002_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
