# Generated by Django 4.2.7 on 2024-01-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extract',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postedBy',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
